#!/bin/bash
# executes simultaneously 20 clients at a specified interval
# or by pressing <Enter>

if [ ! -x ./cam_control ]; then
echo "'cam_control' must be located in the current directory" >&2
exit 1
fi

while true; do
echo exit | tee >(./cam_control>/dev/null) >(./cam_control>/dev/null) \
>(./cam_control>/dev/null) >(./cam_control>/dev/null) \
>(./cam_control>/dev/null) >(./cam_control>/dev/null) \
>(./cam_control>/dev/null) >(./cam_control>/dev/null) \
>(./cam_control>/dev/null) >(./cam_control>/dev/null) \
>(./cam_control>/dev/null) >(./cam_control>/dev/null) \
>(./cam_control>/dev/null) >(./cam_control>/dev/null) \
>(./cam_control>/dev/null) >(./cam_control>/dev/null) \
>(./cam_control>/dev/null) >(./cam_control>/dev/null) \
>(./cam_control>/dev/null) >(./cam_control>/dev/null)
if [ -n "$1" ]; then
sleep $1
else
read line
fi
done

